packages:
  - apps/*
  - packages/*

allowedDeprecatedVersions:
  cache-manager-redis-yet: 4.2.0
  react-beautiful-dnd: 13.1.1

neverBuiltDependencies:
  - canvas

nodeLinker: isolated

catalog:
  '@types/node': 20.17.10
  '@types/react': 18.3.23
  '@types/react-dom': 18.3.7
  antd: 5.22.5
  dayjs: 1.11.13
  react: 18.3.1
  react-dom: 18.3.1
  react-router: 6.28.1
  react-router-dom: 6.28.1
  sequelize: 6.37.5
  string-width: 4.2.3
  strip-ansi: 6.0.1
  wrap-ansi: 7.0.0
  tego: 1.3.55-alpha.0
  '@tego/devkit': 1.3.55-alpha.0
  '@tego/server': 1.3.55-alpha.0
  '@tego/client': 1.3.55-alpha.0
  '@tachybase/test': 1.3.55-alpha.0
  '@tachybase/globals': 1.3.55-alpha.0
  '@tachybase/loader': 1.3.55-alpha.0
  '@tachybase/schema': 1.3.55-alpha.0

catalogMode: strict

cleanupUnusedCatalogs: true

overrides:
  '@types/node': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  antd: 'catalog:'
  dayjs: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  react-router: 'catalog:'
  react-router-dom: 'catalog:'
  sequelize: 'catalog:'
  string-width: 'catalog:'
  strip-ansi: 'catalog:'
  wrap-ansi: 'catalog:'
  tego: 'catalog:'
  '@tego/devkit': 'catalog:'
  '@tego/server': 'catalog:'
  '@tego/client': 'catalog:'
  '@tachybase/test': 'catalog:'
  '@tachybase/globals': 'catalog:'
  '@tachybase/loader': 'catalog:'
  '@tachybase/schema': 'catalog:'
