import { CollectionOptions } from '@tachybase/client';

import ReactEditor from '../components/ComponentEditor';
import MDEditor from '../components/MarkdownEditor';
import { tval } from '../locale';

export const collection: CollectionOptions = {
  name: 'cloudLibraries',
  title: tval('Cloud Library'),
  hidden: false,
  description: null,
  fields: [
    {
      name: 'id',
      type: 'bigInt',
      interface: 'integer',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      uiSchema: {
        type: 'number',
        title: '{{t("ID")}}',
        'x-component': 'InputNumber',
        'x-read-pretty': true,
      },
    },
    {
      name: 'createdAt',
      type: 'date',
      interface: 'createdAt',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      field: 'createdAt',
      uiSchema: {
        type: 'datetime',
        title: '{{t("Created at")}}',
        'x-component': 'DatePicker',
        'x-component-props': {},
        'x-read-pretty': true,
      },
    },
    {
      name: 'createdBy',
      type: 'belongsTo',
      interface: 'createdBy',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      target: 'users',
      foreignKey: 'createdById',
      uiSchema: {
        type: 'object',
        title: '{{t("Created by")}}',
        'x-component': 'AssociationField',
        'x-component-props': {
          fieldNames: {
            value: 'id',
            label: 'nickname',
          },
        },
        'x-read-pretty': true,
      },
      targetKey: 'id',
    },
    {
      name: 'updatedAt',
      type: 'date',
      interface: 'updatedAt',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      field: 'updatedAt',
      uiSchema: {
        type: 'string',
        title: '{{t("Last updated at")}}',
        'x-component': 'DatePicker',
        'x-component-props': {},
        'x-read-pretty': true,
      },
    },
    {
      name: 'updatedBy',
      type: 'belongsTo',
      interface: 'updatedBy',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      target: 'users',
      foreignKey: 'updatedById',
      uiSchema: {
        type: 'object',
        title: '{{t("Last updated by")}}',
        'x-component': 'AssociationField',
        'x-component-props': {
          fieldNames: {
            value: 'id',
            label: 'nickname',
          },
        },
        'x-read-pretty': true,
      },
      targetKey: 'id',
    },
    {
      name: 'name',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Component name'),
      },
      unique: true,
      primaryKey: false,
    },
    {
      name: 'code',
      type: 'text',
      interface: 'textarea',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': ReactEditor,
        title: tval('Component code'),
      },
    },
    {
      name: 'data',
      type: 'json',
      interface: 'json',
      description: tval('Component test data, can be used to mock component data'),
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      defaultValue: null,
      uiSchema: {
        type: 'object',
        'x-component': 'Input.JSON',
        'x-component-props': {
          autoSize: {
            minRows: 5,
          },
        },
        default: '{}',
        title: tval('Component data'),
      },
      jsonb: false,
    },
    {
      name: 'description',
      type: 'text',
      interface: 'textarea',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': MDEditor,
        title: tval('Component documentation'),
      },
    },
    {
      name: 'enabled',
      type: 'boolean',
      interface: 'checkbox',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        'x-component-props': {
          showUnchecked: true,
        },
        type: 'boolean',
        'x-component': 'Checkbox',
        title: tval('Enable'),
      },
    },
    {
      name: 'isClient',
      type: 'boolean',
      interface: 'checkbox',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        'x-component-props': {
          showUnchecked: true,
        },
        type: 'boolean',
        'x-component': 'Checkbox',
        title: tval('Load on client'),
      },
    },
    {
      name: 'isServer',
      type: 'boolean',
      interface: 'checkbox',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        'x-component-props': {
          showUnchecked: true,
        },
        type: 'boolean',
        'x-component': 'Checkbox',
        title: tval('Load on server'),
      },
    },
    {
      name: 'module',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Module name'),
      },
    },
    {
      name: 'serverPlugin',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Server plugin'),
      },
    },
    {
      name: 'clientPlugin',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Client plugin'),
      },
    },
    {
      name: 'component',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Client component'),
      },
    },
    {
      name: 'codeSource',
      type: 'string',
      interface: 'select',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      defaultValue: 'local',
      uiSchema: {
        type: 'string',
        'x-component': 'Select',
        title: tval('Code source'),
        enum: [
          { label: tval('Local code'), value: 'local' },
          { label: tval('Remote code'), value: 'remote' },
        ],
      },
    },
    {
      name: 'codeType',
      type: 'string',
      interface: 'select',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      defaultValue: 'git',
      uiSchema: {
        type: 'string',
        'x-component': 'Select',
        title: tval('Code type'),
        enum: [
          { label: tval('Git'), value: 'git' },
          { label: tval('CDN'), value: 'cdn' },
        ],
      },
    },
    {
      name: 'codeUrl',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Code URL'),
        'x-component-props': {
          placeholder: tval('Code URL placeholder'),
        },
      },
    },
    {
      name: 'codeBranch',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      defaultValue: 'main',
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Code branch'),
        'x-component-props': {
          placeholder: tval('Code branch placeholder'),
        },
      },
    },
    {
      name: 'codePath',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Code path'),
        'x-component-props': {
          placeholder: tval('Code path placeholder'),
        },
      },
    },
    {
      name: 'codeAuthType',
      type: 'string',
      interface: 'select',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      defaultValue: 'token',
      uiSchema: {
        type: 'string',
        'x-component': 'Select',
        title: tval('Authentication type'),
        enum: [
          { label: tval('No authentication'), value: 'none' },
          { label: tval('Bearer Token'), value: 'token' },
          { label: tval('Basic Auth'), value: 'basic' },
        ],
      },
    },
    {
      name: 'codeAuthToken',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input.Password',
        title: tval('Auth token'),
        'x-component-props': {
          placeholder: tval('Auth token placeholder'),
        },
      },
    },
    {
      name: 'codeAuthUsername',
      type: 'string',
      interface: 'input',
      description: null,
      collectionName: 'cloudLibraries',
      parentKey: null,
      reverseKey: null,
      uiSchema: {
        type: 'string',
        'x-component': 'Input',
        title: tval('Auth username'),
        'x-component-props': {
          placeholder: tval('Auth username placeholder'),
        },
      },
    },
  ],
  logging: true,
  autoGenId: true,
  createdAt: true,
  createdBy: true,
  updatedAt: true,
  updatedBy: true,
  template: 'general',
  view: false,
  schema: 'public',
  titleField: 'name',
  filterTargetKey: 'id',
};
