export const EXPORT_LENGTH_MAX = +process.env.EXPORT_LENGTH_MAX || 2000;
export const EXPORT_WORKER_PAGESIZE = +process.env.EXPORT_WORKER_PAGESIZE || 1000;
export const BULK_EXPORT_THRESHOLD = +process.env.BULK_EXPORT_THRESHOLD || 1000;
