name: Auto Approve PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR for whitelisted users
        if: |
          github.actor == 'sealday ' ||
          github.actor == 'baizixv'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
